#!/bin/bash

usage() {
    echo "Usage: $0 [-h] [-o output_file]"
    echo "  -h              Show this help message"
    echo "  -o output_file  Specify output filename (default: spa/loader.html)"
}

output_file="spa/loader.html"

while [[ $# -gt 0 ]]; do
    case $1 in
        -h)
            usage
            exit 0
            ;;
        -o)
            output_file="$2"
            shift 2
            ;;
        -*)
            usage
            exit 1
            ;;
        *)
            break
            ;;
    esac
done

if [ $# -ne 0 ]; then
    usage
    exit 1
fi

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
REPO_ROOT=$( cd -- "$SCRIPT_DIR/../../" &> /dev/null && pwd )

trap "rm -f $SCRIPT_DIR/shell.html" EXIT

# first, build the shell
cat "$SCRIPT_DIR/retro-loader-top.html" "$SCRIPT_DIR/retro-loader-bottom.html" > "$SCRIPT_DIR/shell.html"

# second, build with emscripten
em++ -I "$REPO_ROOT/src" "$REPO_ROOT"/src/*.cpp -o "$REPO_ROOT/$output_file" -s "EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap', 'stringToUTF8']" -s "ASYNCIFY_IMPORTS=['await_input_from_js']" --shell-file "$SCRIPT_DIR/shell.html" -s SINGLE_FILE=1 -s ASYNCIFY -fexceptions
